### ISSUE TITLE
FAQs: questions we should answer

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs#102]
1. How do I find good first issues.
2. My contribution doesn't show how do it get it to.
3. I want to find X language or frameworks data, how do I request it.

This is a list of questions I got when presenting at OSCA.

Answers

1. Look for good first repos or people first. They will lead you to issues worth working on.
2. Indexing by adding your pr to a highlight or creating an insight page.
3. open-Sauced/feedback

**Comment by CBID2** [comment]
> 1. How do I find good first issues.
> 2. My contribution doesn't show how do it get it to.
> 3. I want to find X language or frameworks data, how do I request it.
> 
> This is a list of questions I got when presenting at OSCA.
> 
> Answers
> 
> 1. Look for good first repos or people first. They will lead you to issues worth working on.
> 2. Indexing by adding your pr to a highlight or creating an insight page.
> 3. open-Sauced/feedback

Maybe there can be a FAQ section in the Contributing Guide @bdougie? I just finished my PR for #92 (it's #100), so I'd love to create this section. :)

**Comment by bdougie** [comment]
> Maybe there can be a FAQ section in the Contributing Guide @bdougie? I just finished my PR for #92 (it's #100), so I'd love to create this section. :)

**Comment by CBID2** [comment]
Done @bdougie! :) My PR is #103
