### ISSUE TITLE
docs: Rearrange some sections

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs#104]
The content looks good, I am not everything is place in the correct sections for discoverability. 

Today the Contributing and Technical Guide overlap a lot, and the "Welcome page" now includes a highlight, but after considering, it should be separate. 

New layout

Start Here
- Introduction
- Highlights
- Insights
- Collaborations (Soon)
- FAQs

Community 
- ...that list here

Contributing Guide
- combine the technical and contributing list

I can clean this up after this is merged unless you have time this weekend @CBID2. I am going to be waiting in an airport for awhile and have time.

_Originally posted by @bdougie in https://github.com/open-sauced/docs/issues/103#issuecomment-1596189355_

**Comment by CBID2** [comment]
I'll do it @bdougie

**Comment by bdougie** [comment]
Recommend the FAQs section goes in the start here section too.

**Comment by CBID2** [comment]
Hi @bdougie! :) I've rearranged the sections. See #105.
