### ISSUE TITLE
Bug: Discord link not available 

### ISSUE THREAD

**Issue by oluwasegun31** [open-sauced/docs#108]
### Describe the bug

Seems the discord link in the docs is expired 
![Screenshot_20230619-103026_Chrome](https://github.com/open-sauced/docs/assets/105318972/20c33b27-ee54-4446-b16c-89c7b4c51a55)

### Steps to reproduce

1. Go to https://docs.opensauced.pizza/community/welcome-to-the-community/
2. Scroll to "What's the OpenSauced Community up to?"
3. Click on the discord link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
cc @bdougie

**Comment by AllieGie** [comment]
Has this issue been taken? I'd love to help. It seems the invite is pointing to a channel that is not accessible to everyone.

**Comment by bdougie** [comment]
This has been fixed. The Discord lost some boost, causing the custom link: [discord.gg/opensauced](https://discord.gg/opensauced) to no longer work. I added boosts and it works again. 

Closing this as fixed. I don't think some of that context would have been known. Thanks for bringing this to our attention @oluwasegun31
