### ISSUE TITLE
Feature: Usage gifs

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs#110]
### Type of feature

🍕 Feature

### Current behavior

There is no guide on how to use the product and we need the following features explained via gif.

I will work on this for the 100daysofOSS

### Suggested solution

- [ ] Highlights
- [ ] Collaborations
- [ ] Insight Pages

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
Can you explain a bit more? What should be shown in the Gifs? 
For highlights, we will show how to post it and the interactions,  
what should be shown for the other pages?

**Comment by bdougie** [comment]
It is all a quick 15-30 gif of how the feature works. This will be accompanied with a description. The gif is only meant as a visual representation of the feature. We are doing this with the ai features already.

**Comment by CBID2** [comment]
> It is all a quick 15-30 gif of how the feature works. This will be accompanied with a description. The gif is only meant as a visual representation of the feature. We are doing this with the ai features already.

I'll do it @bdougie

**Comment by CBID2** [comment]
> It is all a quick 15-30 gif of how the feature works. This will be accompanied with a description. The gif is only meant as a visual representation of the feature. We are doing this with the ai features already.

Hey @bdougie. What specific feature are you referring to?

**Comment by bdougie** [comment]
> Suggested solution

 >Highlights
 Collaborations
 Insight Pages


In the OP
