### ISSUE TITLE
Feature: explain the post to linkedin

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/docs#111]
### Type of feature

🍕 Feature

### Current behavior

The post to linkedin feature at the extension is missing the docs. 
Write the docs + add future development suggestions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
This is very helpful
@a0m0rajab. Maybe you can provide information on how to add PRs to LinkedIn? If you need help with this part, let me know:)

**Comment by CBID2** [comment]
Hey @a0m0rajab. Any updates?

**Comment by CBID2** [comment]
@a0m0rajab, are you still working on this?

**Comment by a0m0rajab** [comment]
Yes, I might publish it today, I had to minimize my activity in the last few weeks.

**Comment by CBID2** [comment]
Hey @a0m0rajab. How are things going with the post?

**Comment by a0m0rajab** [comment]
sorry for the late reply I will get back to this when we fix the extension, it's not working right now.

**Comment by a0m0rajab** [comment]
Here is a video explanation that could be used for the docs.
https://github.com/open-sauced/docs/assets/18273833/86efb586-c4f5-4268-a10d-f2773cf3b4ff

**Comment by BekahHW** [comment]
I'm going to close this until that feature is working again.
