### ISSUE TITLE
Bug: incorrect URL to YouTube Channel in docs

### ISSUE THREAD

**Issue by ananfito** [open-sauced/docs#120]
### Describe the bug

The link to OpenSauced's YouTube channel on the ["Welcome to the Community" section](https://docs.opensauced.pizza/community/welcome-to-the-community/#whats-the-opensauced-community-up-to) of the docs is incorrect. 

The current link goes to: https://www.youtube.com/channel/UCQ3x5SxWYK6tUdVJ1V-7n6Q
which is a channel that does not exist: 
![Screen Shot 2023-07-16 at 20 30 09](https://github.com/open-sauced/docs/assets/81890820/cf7e7858-b498-4e92-abcc-b505b43a2428)

The correct link should be: https://www.youtube.com/@OpenSauced

This seems like a quick fix. As someone looking to get started with contributing to open source projects, I'm happy to take this on.

### Steps to reproduce

1. Go to the Community Docs
2. Select 'Getting Started', then select 'Welcome to the Community'
3. Scroll to the [What's the OpenSauced Community up to?](https://docs.opensauced.pizza/community/welcome-to-the-community/#whats-the-opensauced-community-up-to)
4. Click 'YouTube Channel' link

### Browsers

Firefox

### Additional context (Is this in dev or production?)

Production: https://docs.opensauced.pizza/community/welcome-to-the-community/#whats-the-opensauced-community-up-to

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Good catch! Learn more about assigning issues yourself [here](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues)

**Comment by ananfito** [comment]
Thanks. I will .take it then.
