### ISSUE TITLE
Feature: Chrome extension docs need sub folders for the "using" section

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs#122]
### Type of feature

🍕 Feature

### Current behavior

https://docs.opensauced.pizza/chrome-extension/using-the-chrome-extension/

![Screen Shot 2023-07-25 at 8 56 36 AM](https://github.com/open-sauced/docs/assets/5713670/c649ae45-137f-4e90-96da-f9d8e546addb)

### Suggested solution

Should be

```
Chrome extension usage
- using the extension
  - feature 1
  - feature 2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
The simple solution is each feature gets its own page.

**Comment by CBID2** [comment]
.docstake
