### ISSUE TITLE
Feature: Resolve merge conflicts page could be better headed

### ISSUE THREAD

**Issue by dominicduffin1** [open-sauced/docs#124]
### Type of feature

🍕 Feature

### Current behavior

The current page headed "Reserve merge conflicts" also contains a general guide to setting up the repository in git as well as how to resolve merge conflicts.

[https://docs.opensauced.pizza/technical/resolve-merge-conflicts/](https://docs.opensauced.pizza/technical/resolve-merge-conflicts/)

![2023-07-26 19 25 21 docs opensauced pizza 0a3538f48abc](https://github.com/open-sauced/docs/assets/26224873/4b7a310a-0fdf-4a55-8343-f2480f79a453)

### Suggested solution

The content of this page could be broken out into two pages or a more general heading could be used.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Hey @dominicduffin1. I heard from @BekahHW that there's going to be a major overhaul with the docs, so I'd probably put this on hold.

**Comment by dominicduffin1** [comment]
Makes sense @CBID2

**Comment by BekahHW** [comment]
@dominicduffin1 I think this is a good idea. Are you thinking two sections:
- Setting up a repository with Git
- Resolving Merge conflicts

**Comment by dominicduffin1** [comment]
@BekahHW Yes, that's what I was thinking.

**Comment by jdwilkin4** [comment]
Hey @BekahHW ! 

I am interested in working on this 😃

**Comment by CBID2** [comment]
> Hey @BekahHW !
> 
> I am interested in working on this 😃

Hey @dominicduffin1. Do you mind if @jdwilkin4 works on this?

**Comment by dominicduffin1** [comment]
I'm happy for her to work on this @CBID2!

**Comment by CBID2** [comment]
You're assigned @jdwilkin4! :)
