### ISSUE TITLE
Bug: Typo in npm-shrinkwrap.json in Resolve merge conflicts section

### ISSUE THREAD

**Issue by dominicduffin1** [open-sauced/docs#125]
### Describe the bug

There is a typo in the `npm-shrinkwrap.json` filename, which has been written as `npm-shriknwrap.json`.

![2023-07-26 19 39 15 docs opensauced pizza b2c304675187](https://github.com/open-sauced/docs/assets/26224873/1721f9ef-3eb0-4c00-9fcd-29712c23346b)

### Steps to reproduce

1. Go to [https://docs.opensauced.pizza/technical/resolve-merge-conflicts/](https://docs.opensauced.pizza/technical/resolve-merge-conflicts/)
2. Read the first line under the heading

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
Feel free to open a PR to fix it if you want
