### ISSUE TITLE
docs: Link is not properly spaced from the adjacent text in the "Highlight your open source contributions" doc

### ISSUE THREAD

**Issue by Barry-dE** [open-sauced/docs#136]
- The "Effectively Highlights section in our free 'Intro to Open Source' course" link on the "Getting Started" page is not properly spaced from the adjacent text. I have highlighted it  blue in the screenshot below.

- Text that should not be part of the link is embedded within it.

![261405835-9fed245f-660b-46d9-ab9e-460a26e6b3c3](https://github.com/open-sauced/docs/assets/101439132/03fc1a45-d3e5-4a58-aa37-8f0df0b25b9d)

Please find below the link to the document:
https://docs.opensauced.pizza/community/highlights/

### Code of Conduct
- [x] I agree to follow this project's Code of Conduct

### Contributing Docs
- [x] I agree to follow this project's Contribution Docs

**Comment by Barry-dE** [comment]
.take

**Comment by BekahHW** [comment]
Hey @Barry-dE, we appreciate you offering, but this is being fixed along with some other issues in a new PR.

**Comment by Barry-dE** [comment]
Alright
