### ISSUE TITLE
Bug: License information is incomplete

### ISSUE THREAD

**Issue by dominicduffin1** [open-sauced/docs#139]
### Describe the bug

Under the License heading it states that contributors agree to their contributions being licensed under the MIT license, but not all Open Sauced repositories use that license. For example, `open-sauced/app` uses the Apache-2.0 license.

The License subsection in the docs should contain information that reflects the current legal status of the repositories, or more general language such as "you agree that your contributions will be licensed under the repository's license".

### Steps to reproduce

1. Go to https://docs.opensauced.pizza/contributing/introduction-to-contributing/#license

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Hey @dominicduffin1. How are you doing with this?

**Comment by CBID2** [comment]
> Hi @CBID2 , sorry I didn't see I'd been assigned to the issue 😥. Does the team have a preference between adding the different licenses or keeping the language more general?

Hey @dominicduffin1. I'm not too sure. @bdougie, what do you think?

**Comment by dominicduffin1** [comment]
Hi @CBID2 @jpmcb I've opened a PR with some potential general language, let me know what you think! Happy to revise to meet requirements.
