### ISSUE TITLE
docs: YouTube Link Unavailability in FAQ.md

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/docs#140]
### Description 

The YouTube link provided in the `faq.md` file appears to be pointing to a video that is no longer available. Users attempting to access the linked video encounter an error message indicating its unavailability.

<img width="1427" alt="Screenshot 2023-08-22 at 11 31 58" src="https://github.com/open-sauced/docs/assets/106407013/d5587179-19fd-4256-a3d8-4797aff1330c">

**Expected Behavior:**
The linked video should be accessible and play without any issues, providing the intended information to users.

**Actual Behavior:**
Upon clicking the link, users are presented with an error message stating that the video is unavailable.

This issue impacts user experience and the availability of essential information for users seeking assistance through the FAQ section. It's recommended to address this issue promptly to ensure users can access accurate and helpful resources.

### Steps to reproduce

1. Go to https://docs.opensauced.pizza/community/100-days-of-oss/
2. Navigate to the FAQ by left sidebar
3. Locate the YouTube link mentioned 
4. Click on the link to access the video.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by marcusgchan** [comment]
I can confirm that I'm having the same issue

**Comment by RitaDee** [comment]
Hello @bdougie, it seems the YouTube URL isn’t available any longer. Can you please provide me with the correct link? Thank you.

**Comment by bdougie** [comment]
> Hello @bdougie, it seems the YouTube URL isn’t available any longer. Can you please provide me with the correct link? Thank you.

We can remove the link all together. Unless @CBID2 remembers the video or has a better option.

**Comment by CBID2** [comment]
> > Hello @bdougie, it seems the YouTube URL isn’t available any longer. Can you please provide me with the correct link? Thank you.
> 
> 
> 
> We can remove the link all together. Unless @CBID2 remembers the video or has a better option. 

I'll find it @

**Comment by CBID2** [comment]
Hey @RitaDee! I just remembered that I wrote a freeCodeCamp article on how to find good first issues on GitHub. Here it is: https://www.freecodecamp.org/news/how-to-find-good-first-issues-on-github/

**Comment by RitaDee** [comment]
> Hey @RitaDee and @bdougie ! I just remembered that I wrote a freeCodeCamp article on how to find good first issues on GitHub. Here it is: https://www.freecodecamp.org/news/how-to-find-good-first-issues-on-github/

Nice one! @CBID2, I will check it out.

**Comment by CBID2** [comment]
> > Hey @RitaDee and @bdougie ! I just remembered that I wrote a freeCodeCamp article on how to find good first issues on GitHub. Here it is: https://www.freecodecamp.org/news/how-to-find-good-first-issues-on-github/
> 
> 
> 
> Nice one! @CBID2, I will check it out.

Great we can use that one instead

**Comment by RitaDee** [comment]
> > > Hey @RitaDee and @bdougie ! I just remembered that I wrote a freeCodeCamp article on how to find good first issues on GitHub. Here it is: https://www.freecodecamp.org/news/how-to-find-good-first-issues-on-github/
> > 
> > 
> > Nice one! @CBID2, I will check it out.
> 
> Great we can use that one instead

Impressive! 👌 The documentation is clear and helpful, especially for beginners. @bdougie, what are your thoughts? Should we proceed to replace the URL with the one provided by @CBID2?

**Comment by bdougie** [comment]
> 

> . @bdougie, what are your thoughts? Should we proceed to replace the URL with the one provided by @CBID2?

Let's move forward that at as a solution. Thanks @CBID2

**Comment by CBID2** [comment]
You're welcome @bdougie

**Comment by RitaDee** [comment]
> You're welcome @bdougie. @RitaDee, tag me when you make the PR so I can review it.

Sure @CBID2

**Comment by RitaDee** [comment]
I will .take this on.
