### ISSUE TITLE
docs: Explaination on certain parts of the insights page

### ISSUE THREAD

**Issue by CBID2** [open-sauced/docs#142]
### Type of feature

🍕 Feature

### Current behavior

Right now, there isn’t an explainer page on what PR velocity is. This can be confusing for newcomers.

### Suggested solution

Add a explainer page on how PR velocity is 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
That would be helpful.

**Comment by Dilya91433** [comment]
Как найти код
