### ISSUE TITLE
Bug: improvement on docs

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/docs#145]
### Describe the bug

![Screenshot_20230824-140455](https://github.com/open-sauced/docs/assets/72051159/f66febb3-423c-485b-83ad-a5ede098750d)
**Description**
There's no space between the "check out" and "the effectively highlight section"
![Screenshot_20230824-141051](https://github.com/open-sauced/docs/assets/72051159/5965a20b-e5d2-46d8-a44c-45f2777e0376)
**Description**
There's no space between the 'D' and "and"

### Steps to reproduce

1. Go to https://docs.opensauced.pizza/community/highlights/
2. See error

1. Go to https://docs.opensauced.pizza/community/100-days-of-oss/
2. Scroll down
3. See error 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
.take

**Comment by CBID2** [comment]
Hey @dev-phantom! :) Any update on this?

**Comment by dev-phantom** [comment]
> Hey @dev-phantom! :) Any update on this?

Please hold I'll try to fix them today

**Comment by BekahHW** [comment]
@dev-phantom looks like this was fixed in another PR, so I'm going to close the issue.
