### ISSUE TITLE
Bug: overlay of light theme button on opensauced logo(mobile)

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/docs#146]
### Describe the bug

Before the light theme button is click in the nav menu it is displaying on the text Opensauced on mobile
![Screenshot_20230824-145208](https://github.com/open-sauced/docs/assets/72051159/fefc2d75-1e0b-4f83-bd30-dd6be262911c)

### Steps to reproduce

1. Go to https://docs.opensauced.pizza/
2. Click on nav button 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Lokendrakushwah12** [comment]
can you please assign me this issue?

**Comment by dev-phantom** [comment]
You csn use the . take to auto assign yourself to it

**Comment by Lokendrakushwah12** [comment]
how can i do that?

**Comment by dev-phantom** [comment]
> how can i do that?

![Screenshot_20230827-144027](https://github.com/open-sauced/docs/assets/72051159/3d21c4a1-f2a5-400d-8c63-3651df8dfd91)

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by BekahHW** [comment]
I haven't dug into this, but it also seems like it's a docsify issue. @dev-phantom have you checked their repository for open issues or created an issue on their repo?
