### ISSUE TITLE
docs: Ensure Proper Capitalization After a Punctuation Mark

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/docs#154]
### Description

In the faq.md file, I noticed that there is a lack of capitalization after punctuation marks.

<img width="1429" alt="image" src="https://github.com/open-sauced/docs/assets/106407013/f3ebed88-27b6-468c-9b0c-b23b980d3ad8">

### Steps to reproduce

1. Go to "https://docs.opensauced.pizza/community/faqs/"
2. Scroll through the content and observe the usage of punctuation marks.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Vijaykv5** [comment]
Hey I would Like to work on this issue. May you can assign me

**Comment by BekahHW** [comment]
Hey @Vijaykv5, we're making some big updates, and I'm not sure this section is going to keep this language. I'll let you know early next week if this issue is available.

**Comment by BekahHW** [comment]
This was fixed in some of the latest updates
