### ISSUE TITLE
Feature: Add Dev Cards to Getting Started

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#156]
### Type of feature

🍕 Feature

### Current behavior

Currently, we don't have any documentation on Dev cards. We need to add a section.

### Suggested solution

Let's highlight our Dev Card feature: https://insights.opensauced.pizza/user/bekahhw/card

For each section in the Getting Started category, we need to keep in mind the following:
1. Features are for maintainers and contributors at all stages of their journey. Descriptions should be inclusive of that audience.
2. The first part of the feature documentation should explain what the feature is and why it's useful.
3. There should be a screenshot or gif that demonstrates what the feature is or what it does.
4. If necessary, explain why it's important to contributors and maintainers.

Keeping that in mind, let's add Dev Card to the Getting Started panel.

## How to Implement this issue
1. In the repository, go to `docs/community`
2. Add a file called `dev-card.md`
3. In `sidebar.js`, add "community/dev-card", to the `items` array.
4.  In `dev-card.md` replicate the frontmatter in any of the other community files (frontmatter is the part container between the ---) but replace with devcard and update the description.
5. Within that file, create the copy to using the guidelines above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
This is a great idea @BekahHW! :)  This feature could also be for the triage team members too. I'd like to work on this issue.

**Comment by BekahHW** [comment]
It's all you, @CBID2

**Comment by CBID2** [comment]
> It's all you, @CBID2

Thanks @BekahHW! :)

**Comment by Lymah123** [comment]
Can I contribute? 
I hope is beginner friendly.

**Comment by CBID2** [comment]
> Can I contribute? 
> 
> I hope is beginner friendly.

Hi @Lymah123. I've been assigned to this issue. However, I'm eager to receive your review on it once I get the PR 
done.

**Comment by Lymah123** [comment]
@CBID2,  alright!
Looking forward that. Thank you.

**Comment by Lymah123** [comment]
@CBID2 . Alright.

Looking forward to that. Thank you.
