### ISSUE TITLE
feat: adding edit this page buttons

### ISSUE THREAD

**Issue by CBID2** [open-sauced/docs#159]
### Type of feature

🍕 Feature

### Current behavior

There’s no editing buttons.

### Suggested solution

I think we should add one. To stay consistent with the other repos.

![edit this page](https://github.com/open-sauced/.github/assets/105683440/0b4c664d-84d5-4c6b-a5d4-762479f8935e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
@open-sauced/triage, what do you think?

**Comment by takanome-dev** [comment]
@CBID2 what do you mean? I can see the edit button in the docs :thinking:

**Comment by CBID2** [comment]
> @CBID2 what do you mean? I can see the edit button in the docs :thinking: 

Ooh that was meant for the intro course repo 🤦🏾‍♀️

**Comment by CBID2** [comment]
> @CBID2 what do you mean? I can see the edit button in the docs :thinking: 

Is there a way you can transfer this issue to that repo @takanome-dev?

**Comment by takanome-dev** [comment]
> Is there a way you can transfer this issue to that repo @takanome-dev?

Nope, maybe @bdougie or @BekahHW can do it

**Comment by BekahHW** [comment]
@CBID2 the docs repo has it because we're using docsify. Because the intro course is just markdown, we'd have to hack it together as a link.

**Comment by CBID2** [comment]
> @CBID2 the docs repo has it because we're using docsify. Because the intro course is just markdown, we'd have to hack it together as a link. 

Ooh ok @BekahHW.

**Comment by CBID2** [comment]
Hi @BekahHW! :) I was going to do a PR for this.

**Comment by BekahHW** [comment]
@CBID2 can you recreate the issue on the intro repository?

**Comment by CBID2** [comment]
> @CBID2 can you recreate the issue on the intro repository?

Hey @BekahHW. I think you can transfer it to that repository by clicking on Transfer issue

**Comment by BekahHW** [comment]
I can't from the mobile app, so it'll have to wait until I have my computer on.
