### ISSUE TITLE
Feature: Add a page for Hacktoberfest resources in the Community Section

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#168]
### Type of feature

🍕 Feature

### Current behavior

With Hacktoberfest coming up, it would be great to have a page devoted to resources for folks new to Hacktoberfest. 

### Suggested solution

At OpenSauced, we've written quite a few blog posts that can be aggregated in one place. 

Suggested Sections:
1. What is Hacktoberfest? (link to https://dev.to/opensauced/how-to-participate-in-hackoberfest-13hm)
2. First Time Contributors (links to OpenSauced Dev resources on git, intro course, github)
4. Why should you participate in Hacktoberfest (link to OpenSauced Dev resources on the value of contributing)
5. Understanding Open Source(links to OpenSauced Dev resources on things like contrib guides, maintainer resources, etc.)
6. Start contributing! (link to https://insights.opensauced.pizza/pages/BekahHW/655/dashboard)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
I'll do it @BekahHW! 😀

**Comment by CBID2** [comment]
Hi @BekahHW! :) I made the PR. It's #179
