### ISSUE TITLE
docs: streamline #100DaysOfOSS activities with parallel structure

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/docs#170]
### Description

In order to enhance the clarity and readability of the doc regarding the various ways to participate in the #100DaysOfOSS challenge, we should adopt a consistent and parallel structure. This ensures that the list of participation options is not only easier to understand but also aesthetically pleasing.

<img width="1422" alt="Screenshot 2023-09-22 at 22 35 20" src="https://github.com/open-sauced/docs/assets/106407013/1e1f6729-7754-40ca-a53b-578d2278c737">

### Here's the revised content with a parallel structure:

- Create content:
    - Give a talk or presentation on OSS.
    - Participate in or even start a Twitter Space.
    - Write a blog post or create a video.
- Maintain a project:
   - Review pull requests.
   - Triage issues.
  - Respond to questions.
  
By making this adjustment, the content is now structured consistently, making it easier to understand and follow.

### Steps to reproduce

1. Go to 'https://docs.opensauced.pizza/community/100-days-of-oss/.'

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Hi @RitaDee! :) This a great idea! :) Placing the different types of contributions into different categories would be very helpful. I think it can also be organized like this:
 ## Content Creation
Love creating content? Here's how you can use this skill for the challenge: 
-  Give a talk or presentation on OSS.
- Participate in or even start a Twitter Space.
- Write a blog post or create a video.
## Project management
Want to improve your project management skills? Need to get better at communicating or giving feedback to others? Here's how you can use this skill for the challenge:

- Review pull requests.
- Triage issues.
- Respond to questions.

**Comment by CBID2** [comment]
> Hi @RitaDee! :) This a great idea! :) Placing the different types of contributions into different categories would be very helpful. I think it can also be organized like this:
> 
> ## Content Creation
> Love creating content? Here's how you can use this skill for the challenge:
> 
> * Give a talk or presentation on OSS.
> * Participate in or even start a Twitter Space.
> * Write a blog post or create a video.
> 
> ## Project management
> Want to improve your project management skills? Need to get better at communicating or giving feedback to others? Here's how you can use this skill for the challenge:
> 
> * Review pull requests.
> * Triage issues.
> * Respond to questions.

What do you think @BekahHW?

**Comment by RitaDee** [comment]
> > Hi @RitaDee! :) This a great idea! :) Placing the different types of contributions into different categories would be very helpful. I think it can also be organized like this:
> > ## Content Creation
> > Love creating content? Here's how you can use this skill for the challenge:
> > 
> > * Give a talk or presentation on OSS.
> > * Participate in or even start a Twitter Space.
> > * Write a blog post or create a video.
> > 
> > ## Project management
> > Want to improve your project management skills? Need to get better at communicating or giving feedback to others? Here's how you can use this skill for the challenge:
> > 
> > * Review pull requests.
> > * Triage issues.
> > * Respond to questions.
> 
> What do you think @BekahHW?

Great stuff @CBID2, you just made it spicy.

**Comment by CBID2** [comment]
> > > Hi @RitaDee! :) This a great idea! :) Placing the different types of contributions into different categories would be very helpful. I think it can also be organized like this:
> 
> > > ## Content Creation
> 
> > > Love creating content? Here's how you can use this skill for the challenge:
> 
> > > 
> 
> > > * Give a talk or presentation on OSS.
> 
> > > * Participate in or even start a Twitter Space.
> 
> > > * Write a blog post or create a video.
> 
> > > 
> 
> > > ## Project management
> 
> > > Want to improve your project management skills? Need to get better at communicating or giving feedback to others? Here's how you can use this skill for the challenge:
> 
> > > 
> 
> > > * Review pull requests.
> 
> > > * Triage issues.
> 
> > > * Respond to questions.
> 
> > 
> 
> > What do you think @BekahHW?
> 
> 
> 
> Great stuff @CBID2, you just made it spicy.

Lol I guess I did @RitaDee 😂

**Comment by BekahHW** [comment]
This is a great idea and I love how it demonstrates the skillset.

**Comment by RitaDee** [comment]
Can I  take this on @BekahHW?

**Comment by RitaDee** [comment]
> Want to improve your project management skills? Need to get better at communicating or giving feedback to others? Here's how you can use this skill for the challenge:
> 
> * Review pull requests.
> * Triage issues.
> * Respond to questions.



Take a look at https://github.com/open-sauced/docs/issues/169

Can I add this fix here?

https://github.com/open-sauced/docs/issues/170

What do you think?

**Comment by CBID2** [comment]
> > Want to improve your project management skills? Need to get better at communicating or giving feedback to others? Here's how you can use this skill for the challenge:
> > 
> > * Review pull requests.
> > * Triage issues.
> > * Respond to questions.
> 
> Take a look at #169
> 
> Can I add this fix here?
> 
> #170
> 
> What do you think?

I think it's best to do a separate PR for #169.
