### ISSUE TITLE
Bug: Link redirects user to an unavailable page

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/docs#181]
### Describe the bug

When users click on the link [CSS variables](https://github.com/open-sauced/open-sauced/blob/HEAD/src/styles/variables.js), they are redirected to an unavailable page. This is causing a broken user experience as the user is unable to access the intended content.

<img width="1432" alt="Screenshot 2023-09-28 at 23 20 41" src="https://github.com/open-sauced/docs/assets/106407013/7f33bda1-6ad0-4302-92d2-fbb03e26c5a6">

### Steps to reproduce

1. Go to "https://docs.opensauced.pizza/contributing/introduction-to-contributing/"
2. Click on the link [CSS variables](https://github.com/open-sauced/open-sauced/blob/HEAD/src/styles/variables.js).

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
@CBID2 , can I hop on this too? : )

**Comment by Lymah123** [comment]
> @CBID2 , can I hop on this too? : )

@BekahHW and @CBID2 , can I ? If yes, please assign me.

**Comment by Lymah123** [comment]
Hi @BekahHW , I have made the changes to the issue.
