### ISSUE TITLE
Docs: Grammar correction in sentence

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/docs#182]
### Description

<img width="1436" alt="image" src="https://github.com/open-sauced/docs/assets/106407013/cdfe5f4b-f358-4bdf-9f69-9d198e2e6339">

There's a minor grammatical issue. The sentence reads:

"GitHub will conveniently display only you merge conflict changes."

It should be corrected to:

"GitHub will conveniently display only your merge conflict changes."

This change adds the necessary possessive form "your" before "merge conflict changes" to make the sentence grammatically accurate.

### Steps to reproduce

1. Go to "https://docs.opensauced.pizza/technical/resolve-merge-conflicts/"
2. Under the subheading "Review your pull request," check the second sentence 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
@CBID2 , can I work on the issue?

**Comment by CBID2** [comment]
I think you can add it to your race conditions PR

**Comment by Lymah123** [comment]
> I think you can add it to your race conditions PR

Okay. Thank you!

**Comment by CBID2** [comment]
> > I think you can add it to your race conditions PR
> 
> 
> 
> Okay. Thank you!

Remember to link this issue in your PR form too :)

**Comment by Lymah123** [comment]
> > > I think you can add it to your race conditions PR
> > 
> > 
> > Okay. Thank you!
> 
> Remember to link this issue in your PR form too :)

Alright. Thank you!
