### ISSUE TITLE
Docs: "Race condition" terminology not clear

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/docs#183]
### Description

<img width="1433" alt="image" src="https://github.com/open-sauced/docs/assets/106407013/440f3188-bb16-4a15-954e-3269d8fcbc61">

In the provided instructions, the term "race condition" is mentioned without a clear context or definition. It's essential to provide clarification on the meaning of "race condition" in this specific context to ensure that all contributors understand its significance accurately.

### Steps to reproduce

1. Go to "https://docs.opensauced.pizza/maintainers/setting-up-a-new-repository/"
2. Scroll to the subtopic "Syncing labels with opensauced.pizza" and read through the last (third) list item

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
Hi, @CBID2 and @RitaDee! Can I work on the issue?

**Comment by CBID2** [comment]
> Hi, @CBID2 and @RitaDee! Can I work on the issue?

Sure @Lymah123

**Comment by CursedSpiderBoi** [comment]
Verified
