### ISSUE TITLE
Feature: connections feature

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#190]
### Type of feature

🍕 Feature

### Current behavior

Currently not included in documentation.

### Suggested solution

Show how to use the connections feature, provide context for the value. Something like:
> The Connections feature serves as a networking hub for the open-source community. Whether you're seeking mentorship,  trying to grow your project or network, find opportunities to collaborate or work together, or want to learn more about what others are working on, this feature offers a streamlined way to connect.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
Hi @BekahHW, can I work on the issue?

**Comment by Lymah123** [comment]
> Hi @BekahHW, can I work on the issue?

@CBID2, I'd like to.

**Comment by CBID2** [comment]
Actually @Lymah123. I wanted to give this a try. You can review it once I get the PR up 😊

**Comment by Lymah123** [comment]
> Actually @Lymah123. I wanted to give this a try. You can review it once I get the PR up 😊
Alright. :)
