### ISSUE TITLE
Feature: Clarify Interpretation of PR Velocity and PR Overview Elements

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/docs#194]
### Type of feature

📝 Documentation

### Current behavior

The documentation for PR Velocity and the PR Overview is currently missing crucial context related to the elements displayed, and it's important to provide users with a comprehensive understanding of these elements. The current documentation should be updated to reflect the elements displayed in the PR Velocity and PR Overview correctly.

**Original Text:**
(Include the section mentioning PR Velocity from the screenshot)
https://docs.opensauced.pizza/community/pr-velocity/

**Additional Context:**
Enhancing this documentation will ensure that users can accurately interpret and benefit from the information presented in both the PR Velocity and PR Overview, making it a more user-friendly tool for assessing the state of ongoing and completed contributions.

### Suggested solution

**Revised Text:**
(Include the same section but add the following clarifying paragraph)

"In the context of the PR Velocity, when you see a value like "66% in 10 days," it signifies that within a period of 10 days, 66% of the PRs (Pull Requests) were successfully merged out of the total PR count. This indicates the efficiency and speed of the pull request workflow.

In the PR Overview, it displays the following key information:

- "6 PRs" indicates the total number of pull requests in the repository.
- The green line represents the number of open pull requests.
- The red line represents the number of closed pull requests.
- The purple line represents the number of merged pull requests.
- Total percentage of pull requests" summarizes the open, closed, and merged PRs relative to the total number of pull requests in the repository.

Understanding these elements is essential for users to quickly assess the status of pull requests and contributions within the repository."

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
@CBID2

**Comment by CBID2** [comment]
> @CBID2 

You want to work on this @dev-phantom?

**Comment by dev-phantom** [comment]
> > @CBID2
> 
> You want to work on this @dev-phantom?

Nope

**Comment by CBID2** [comment]
Ok, hey @BekahHW, I want to implement this information but I want to hear your perspective before I submit a PR.

**Comment by dev-phantom** [comment]
@BekahHW please can you reopen the issue and close it as not planned as this issue wasn't fix or fix here

**Comment by BekahHW** [comment]
The issue is linked in the app repo. This is not an issue for docs.

**Comment by dev-phantom** [comment]
> The issue is linked in the app repo. This is not an issue for docs.

That's correct. The issue mentioned is linked to the app repository, not the documentation. When I mentioned that it should be closed as 'not planned,' I meant that this specific feature or task was not part of the plan for this particular repository. It hasn't been implemented here and won't be, which is why i suggest this issue should be closed as 'not planned' rather than 'completed.'

**Comment by CBID2** [comment]
> > The issue is linked in the app repo. This is not an issue for docs.
> 
> That's correct. The issue mentioned is linked to the app repository, not the documentation. When I mentioned that it should be closed as 'not planned,' I meant that this specific feature or task was not part of the plan for this particular repository. It hasn't been implemented here and won't be, which is why i suggest this issue should be closed as 'not planned' rather than 'completed.'

Done @dev-phantom
