### ISSUE TITLE
Feature: Add a Section for Open Source Terminology

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/docs#195]
### Type of feature

📝 Documentation

### Current behavior

The existing documentation lacks a dedicated section that explains the terms commonly used in open source projects. We recommend adding a comprehensive glossary of open source terms to provide users, especially those new to open source development, with a clearer understanding of the vocabulary they may encounter.

**Why This Is Needed:**
The inclusion of an open source terminology section is vital for several reasons:

1. **Clarity for Newcomers:** Newcomers to open source development may not be familiar with these terms. Having a dedicated section will help them understand the core concepts quickly.

2. **Accessibility:** Open source should be accessible to all. Clear explanations of terms will make open source projects more inclusive.

3. **Effective Communication:** It will facilitate better communication within open source communities, reducing misunderstandings and promoting efficient collaboration.

4. **Promoting Best Practices:** Understanding these terms is crucial for following best practices in open source development and contributing effectively.

5. **Community Growth:** A well-informed community is more likely to grow and thrive, benefiting both developers and the projects they contribute to.

Adding a section for open source terminology will enhance the documentation's comprehensiveness and usability, making it a valuable resource for individuals looking to get involved in open source projects.

### Suggested solution

I propose the creation of a new section in the documentation specifically dedicated to "Open Source Terminology." This section should include concise explanations for the following common open source terms:

1. **Open Source:** Clarify the concept of open source software and its fundamental principles, such as transparency, collaboration, and accessibility.

2. **Pull Request (PR):** Describe what a pull request is, its purpose, and its role in the open source development process.

    - **Accepted PRs:** Explain that accepted PRs are pull requests that have been reviewed and merged into the project, representing successful contributions.

    - **Draft PRs:** Detail what draft PRs are and their role as early-stage contributions that are not yet ready for review and merge.

3. **Fork:** Explain what forking a repository means and how it is used in open source projects.

4. **Contributor:** Define a contributor, detailing their role and significance in open source communities.

5. **Maintainer:** Explain the role of project maintainers, including their responsibilities and how they manage open source projects.

6. **Repository:** Provide a clear definition of a repository in the context of version control and open source projects.

7. **Issue:** Describe what an issue is, how it is used to track tasks, bugs, and discussions in open source projects.
8. **License:** Explain open source licenses, their importance, and the various types commonly used.

9. **Community:** Define an open source community and its role in fostering collaboration and development.

10. **Spam:** Define "spam" in the context of open source projects, explaining unwanted, irrelevant, or disruptive content.

11. **PR Overview:** Explain PR Overview as a summary of the status of pull requests in a repository, including open, closed, and merged PRs.

12. **PR Velocity:** Describe PR Velocity as a metric measuring the efficiency of merging PRs, including the percentage and time taken.

13. **Activity:** Define "activity" as events, interactions, or changes within an open source project, which can include pull requests, issues, and more.

14. **List:** Explain what a "list" is in the context of opensauced.

15. **Insight:** Explain what a "insight" is in the context of opensauced.

16. **Issue:** Provide a clear definition of "issue" in the context of open source projects, often used for tracking tasks, bugs, and discussions.
Etc 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
Looks like we have something similar in 
[Opensauced intro glossary](https://intro.opensauced.pizza/#/10-glossary)
Should I close this issue and and create a new one there telling them to update the glossary

**Comment by CBID2** [comment]
> Looks like we have something similar in [Opensauced intro glossary](https://intro.opensauced.pizza/#/10-glossary) Should I close this issue and and create a new one there telling them to update the glossary Although the intro glossary only covers open source terms But this will cover opensauced terms I just adding a section with just opensauced term then make reference to the intro glossary in the section I don't know if you understand my point?

I was just about to mention the glossary @dev-phantom lol! 😆 I'm not sure what term you're referring to though.

**Comment by dev-phantom** [comment]
> > Looks like we have something similar in [Opensauced intro glossary](https://intro.opensauced.pizza/#/10-glossary) Should I close this issue and and create a new one there telling them to update the glossary Although the intro glossary only covers open source terms But this will cover opensauced terms I just adding a section with just opensauced term then make reference to the intro glossary in the section I don't know if you understand my point?
> 
> I was just about to mention the glossary @dev-phantom lol! 😆 I'm not sure what term you're referring to though.

Sorry about this
Closing this issue
