### ISSUE TITLE
feat: reorganize docs

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#199]
For Ref: https://app.clickup.com/20553800/v/dc/kk828-8391

**Comment by CBID2** [comment]
> For Ref: https://app.clickup.com/20553800/v/dc/kk828-8391

Hey @BekahHW. The ClickUp link does not work

**Comment by BekahHW** [comment]
@CBID2 it's for internal use only.

**Comment by CBID2** [comment]
> @CBID2 it's for internal use only.
> 
> 

Thanks for clarifying @BekahHW
