### ISSUE TITLE
Feature: Add glossary to getting started section

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#200]
### Type of feature

🍕 Feature

### Current behavior

There's not currently a glossary of terms. Although tooltips are being implemented on the app side, we can implement it here as well

### Suggested solution

Rather than having a separate file for each term, we could have a glossary in the `getting started section.`

1. Create `glossary.md` in the `getting started section.`
2. The title should be "OpenSauced Glossary"
3. Description: Welcome to the glossary, where we define concepts used on our platform to help you get the most out of OpenSauced.
4. Add the page to `sidebar.js`

## Terms to include
- PR Velocity
- Activity
- PR Overview
- Alumni Contributors
- Active Contributors
- New Contributors
- Churned Contributors
- Insights
- Lists

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
Hi @BekahHW , Can I work on the issue?

**Comment by BekahHW** [comment]
@Lymah123 it's on hold until the new organization PR is merged in.

**Comment by Lymah123** [comment]
> @Lymah123 it's on hold until the new organization PR is merged. 

Okay. Thanks.

**Comment by BekahHW** [comment]
@Lymah123 are you still interested in working on this?

I've added some of the definitions in the comments of this PR: https://github.com/open-sauced/app/issues/1806#issuecomment-1804449067

**Comment by Lymah123** [comment]
> @Lymah123 are you still interested in working on this?
> 
> I've added some of the definitions in the comments of this PR: [open-sauced/app#1806 (comment)](https://github.com/open-sauced/app/issues/1806#issuecomment-1804449067)

Hi @BekahHW , yes I'm still interested.

**Comment by Lymah123** [comment]
Hi @BekahHW , I can't find `getting started section` in the docs repo, but there is `getting started section` in intro repo.

Or should I put it under `introduction.md section`?

You suggested the `glossary. md` should be inside the `getting started section.`

**Comment by Lymah123** [comment]
> Hi @BekahHW , I can't find `getting started section` in the docs repo, but there is `getting started section` in intro repo.
> 
> Or should I put it under `introduction.md section`?
> 
> You suggested the `glossary. md` should be inside the `getting started section.`

Hi @CBID2 , can you check the question please

**Comment by BekahHW** [comment]
In the repo, it's the community folder.

**Comment by BekahHW** [comment]
Sorry about that. We'll be renaming and changing up some of this stuff soon. 

On the site, community shows up as Getting Started.
