### ISSUE TITLE
Add  info on adding teammates to insights page

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#202]
In the Insights feature page, we should include a portion that says something like:

> After you've created your insights page, share it with your team. 

1. Add an explanation why
2. Add directions
3. Add a link to this video: https://www.youtube.com/watch?v=L5ztLP1O7BY

**Comment by Lymah123** [comment]
Hi @BekahHW , can I work on the issue?

**Comment by Lymah123** [comment]
@adiati98 

This is the next issue I will be working on.
