### ISSUE TITLE
Feature: Create a Guide for Using OpenSauced for Job Seekers

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#203]
### Type of feature

🍕 Feature

### Current behavior

We don't currently have any official guides on using OpenSauced.

### Suggested solution

Create a guide on using OpenSauced for Job Seekers. The guide should include:

1. An introduction to matching job requirements to skills
2. How to use each OpenSauced feature to relate to your job search
3. How to share your OpenSauced profile

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
I've been wanting to learn how to OpenSauced in the job search, so this guide would be very helpful @BekahHW.

**Comment by jdwilkin4** [comment]
I love this idea. 

Can I work on this @BekahHW? 😀
Or does it still need to be triaged?

**Comment by BekahHW** [comment]
The chart in this post would be a good thing to include. We can remove or add things as we see fit.

https://dev.to/opensauced/job-seekers-worksheet-build-your-resume-with-open-source-5am5
