### ISSUE TITLE
feature: Maintainers Guide on Using OpenSauced

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#204]
## Type of feature
🍕 Feature

## Current behavior
We don't currently have any official guides on using OpenSauced.

## Suggested solution
Create a guide on using OpenSauced for Maintainer. The guide should include:

- An introduction creating a healthy maintainer environment
- How to use each OpenSauced feature to relate to your project
- How to share your OpenSauced profile

**Comment by Barry-dE** [comment]
Hello BekaHW, I would love to work on this. Please point me in the direction of any resource that would aid me in achieving this.
