### ISSUE TITLE
Feature: Add OpenSauced for Contributors Guide

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#208]
### Type of feature

🍕 Feature

### Current behavior

We currently don't have a clear guide for contributors.

### Suggested solution

Following the [Maintainers Guide](https://docs.opensauced.pizza/maintainers/) as an example, create a guide for contributors. Try to follow the same sections and headings for consistency.

In addition to the features included in the Maintainers card, also include the dev card.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ATREAY** [comment]
Hey @BekahHW, I'd love to help out with creating this guide, if such an opportunity is available.

**Comment by BekahHW** [comment]
@ATREAY how are things going?

**Comment by ATREAY** [comment]
Hey @BekahHW,

Unfortunately, my college has unexpectedly announced exams, and I anticipate being unable to dedicate time to this task for the next week. If it is acceptable, I am committed to working on this issue after the exams are over. 
Alternatively, feel free to assign this issue to another interested individual.

I sincerely apologize for any inconvenience this may cause.

**Comment by CBID2** [comment]
.take

**Comment by CBID2** [comment]
> Hey @CBID2 we jut merged in the [guide for job seekers](https://docs.opensauced.pizza/job-seekers-guide/job-seekers-guide-introduction/). SO you might want to take a look at that and the[ maintainers guide.](https://docs.opensauced.pizza/maintainers/maintainers-guide-to-open-sauced/).
> 
> 
> 
> Let me know if you have questions.
> 
> 
> 
> 

You mean look at those two guides as references @BekahHW?

**Comment by BekahHW** [comment]
@CBID2 yep!
