### ISSUE TITLE
Bug: Link to PR velocity term in the Dev card section leads to "Page Not Found"

### ISSUE THREAD

**Issue by jdwilkin4** [open-sauced/docs#219]
### Describe the bug

The link for the [PR velocity term](https://docs.opensauced.pizza/welcome/glossary/#pr-velocity) is incorrect in the [Dev Card section](https://docs.opensauced.pizza/features/dev-card/) and it shows extra unnecessary path information.

<img width="946" alt="Screenshot 2023-11-30 at 9 20 07 PM" src="https://github.com/open-sauced/docs/assets/67210629/19b9e0c9-5252-4937-8e9f-34e6756b356e">

## Solution

Remove the  extra`(../../docs/welcome/glossary/#pr-velocity.md)` and fix the path to the PR velocity link.  
Here is the markdown file that needs fixing
https://github.com/open-sauced/docs/blob/main/docs/features/dev-card.md

### Steps to reproduce

1. Go to the [Dev Card feature section](https://docs.opensauced.pizza/features/dev-card/)
2. Click on the link in the first paragraph
3. It will open a "Page Not Found"

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by MrCyberlord** [comment]
.take

**Comment by ptech12** [comment]
I'm interested in doing this. Can you assign me
