### ISSUE TITLE
Feature: Add image and instructions on how to get your to DevCard page. 

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#222]
### Type of feature

🍕 Feature

### Current behavior

Currently, we don't show the user how to get their dev card.

## To Do
- [ ] Change language
- [ ] Add Image

### Change Language

Currently, we have this language: "Eager to get your Dev Card? Create it today and share with your network!"

Let's change that to:

Eager to get your Dev Card? Here's how you can get yours today:

1. Log in to your OpenSauced account. 
2. Navigate to your profile. (The URL should be https://app.opensauced.pizza/user/{username}
3. Click the DevCard icon on your profile image.

## Add Image

After that, include a screenshot of the image with an indication of where that is.

The image should look similar to the one below. You should add the image to the `img` folder  (`docs/static/img`) and title it `get_dev_card.svg`. 

![Screenshot 2023-12-05 at 12 30 40 PM](https://github.com/open-sauced/docs/assets/34313413/d58b3d84-3161-4392-8be9-6a56ef58ffcd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Haimantika** [comment]
Hi @BekahHW I would like to give this issue a try, if @Lymah123 is not working on it :)

**Comment by Haimantika** [comment]
.take
