### ISSUE TITLE
feat: Update Highlights docs

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#224]
## Current

We have "Fill content" and "Add and Summarize" buttons in the "Highlight suggestions" section that are not covered here.

_Originally posted by @adiati98 in https://github.com/open-sauced/docs/pull/213#discussion_r1405228070_

## Solution

- [x] add directions on adding a highlight from the highlight suggestion. 
- [ ] Explain both the "Fill content" and "Add and Summarize" buttons
- [x] Remove the existing gif for the highlight
- [x] Create a new gif with one that shows the suggestions and name it "highlight.gif". (The naming is important so we don't break anything that's been linked elsewhere.)

**Comment by oluwatobi2001** [comment]
Hi can i take this up?

**Comment by CBID2** [comment]
> Hi can i take this up?

Hey @oluwatobi2001. Just type `.take` in the comment section and you'll be automatically assigned.

**Comment by CBID2** [comment]
.take

**Comment by vivitt** [comment]
Hi @oluwatobi2001, are you still interested in working on this issue?
If not, I would like to take it. Let me know. Thanks!

**Comment by oluwatobi2001** [comment]
Yes, I'm still interested.

**Comment by vivitt** [comment]
.take

**Comment by vivitt** [comment]
Hello! I have a couple of questions before submitting a PR for this issue:

First, I understand that this change should prioritize the Highlight suggestions section usage, so the current indications should remain in the docs but maybe below the new instructions and the new gif. Do you think this approach is correct, or does anyone have any other thoughts on this?

Second, I encountered an issue while using the "Add and summarize" button. As shown in the gif below, I receive an error message when I try to summarize a PR:  
![gif_01](https://github.com/open-sauced/docs/assets/91918142/b5570897-4ccb-4af5-9156-442e40bdd474)

I am also not able to use the Auto-Summarize feature if I paste the link manually:
![gif_02](https://github.com/open-sauced/docs/assets/91918142/f7c49a54-d11e-4a1b-9495-ebd3e6cf4e85)

So I wanted to check if I am following the right steps here or if I am missing something.

Thanks a lot for any help :)

**Comment by adiati98** [comment]
Hey @vivitt,

Sorry, I don't quite understand what do you mean in the first question. Can you elaborate more?

As for your question about summarize, I can confirm that I also have the same issue.
You might want to create an issue on our [app repo](https://github.com/open-sauced/app) to report this. 😊

**Comment by vivitt** [comment]
Hello @adiati98 !
Didn't find a similar open issue, so I [created one](https://github.com/open-sauced/app/issues/3568).

For my first question, I was confused because the [How to Add a Highlight](https://opensauced.pizza/docs/features/highlights/) section now includes a set of bullet points and a GIF that need to be replaced. My bad for not explaining that clearly. 

What I wanted to know is if should I document the "Fill Content" and "Add and Summarize" buttons by adding more bullet points below the existing ones, or is it better to reorganize the section by first documenting the "Highlight Suggestions" buttons and then the option of manually pasting a link?

Thanks!

**Comment by adiati98** [comment]
Hey @vivitt,

I think reorganize would be better.

We can say something like, "There are two ways to add highlights, with the Highlight suggestions and manually." You can experiment with adding `h3` here if it makes things clearer.
Then, follow the checkbox on the issue.

The instructions are all in bullet points for better read and understanding.

You can draft it first, and we'll see how we can improve and clarify them.
And feel free to let me know if you have further questions or need help. ✨

**Comment by vivitt** [comment]
Thanks @adiati98! Here's a possible draft for organizing the instructions:

```
## How to Add a Highlight

There are two ways to adding highlights:

### Using Highlight Suggestions

- Go to [OpenSauced's Highlights feed](https://app.opensauced.pizza/feed).
- Click the "Post a highlight to show your work!" input.
- Search the relevant blog post, pull request, or issue in the "Highlight suggestions" section.
- Either use the "Fill content" button to paste the suggested link or the "Add and Summarize" button to paste the link and Auto-Summarize the content.

![highlights demo](example.gif)

### Adding a Link Manually

- Go to [OpenSauced's Highlights feed](https://app.opensauced.pizza/feed).
- Click the "Post a highlight to show your work!" input.
- Paste the URL to your blog post, pull request, or issue in the bottom input.
- Either use our Auto-Summarize feature or write your own summary.

```

What do you think? Any suggestions?
Thanks :)

**Comment by adiati98** [comment]
Hey @vivitt,

Sorry for taking a while to respond.

This looks great! ✨ 
However, I can see a room for improvement based on below things:

- The first two bullet points in each method are the same. We might be able to avoid repetition here.
- The "Highlight suggestions" only suggest issue and PRs, not blog posts.

Below is a raw suggestion. Feel free to give other ideas.

```markdown
## How to Add a Highlight

First, go to [OpenSauced's Highlights feed](https://app.opensauced.pizza/feed), then click the "Post a highlight to show your work!" input.

There are two ways to adding highlights:

### 1. Using Highlight Suggestions

- Search the pull request or issue that you want to add in the "Highlight suggestions" section.
- Click the "Fill content" button to paste the suggested link or the "Add and Summarize" button to paste the link and auto-summarize the content.

:::note

The "Highlight suggestions" are only suggesting issues and pull requests that you created. For blog posts, you need to add them manually.

:::

![highlights demo](highlight.gif)

### 2. Adding a Link Manually

- Paste the URL to your blog post, pull request, or issue in the bottom input.
- Either use our Auto-Summarize feature or write your own summary.
```
