### ISSUE TITLE
Feature: change screenshot in "Activity" subsection 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/docs#270]
### Type of feature

🍕 Feature

### Current behavior

The Activity subsection in the Maintainer's Guide describes the three tabs as Overview, Activity, and Contributor. Since the new workspace feature are released these tabs are now called, Overview, Activity, and Highlights. 

### Suggested solution

Per [@adiati98's suggestion in #262](https://github.com/open-sauced/docs/pull/262#discussion_r1510417882), the following change need to be done:

- [ ] Replace the screenshot [in the Activity section](https://github.com/open-sauced/docs/blob/fe55e8f9611976e5ee0fd8fd5f88e9b7f1d545ac/docs/maintainers/maintainers-guide.md?plain=1#L123) with the new one below.

   ![list-graph](https://github.com/open-sauced/docs/assets/45172775/d6a53964-b55d-471f-a905-67f5dae78e73)

   

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
You’re assigned @Arvind644

**Comment by adiati98** [comment]
@Arvind644 FYI, I replaced the image with the new one. Thanks!

**Comment by adiati98** [comment]
Hey @Arvind644 

Just want to let you know that because we don't hear anything from you regarding to this issue, we're unassigning you from it.

**Comment by DevJSter** [comment]
@CBID2 Can you assign me this issue ?

**Comment by CBID2** [comment]
> @CBID2 Can you assign me this issue ?

@adiati98 can you assign this issue please?

**Comment by adiati98** [comment]
Hi there,

Please read our [contributing guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing) if you'd like to work on any issue in our repo. ✨️

**Comment by DevJSter** [comment]
Hey @adiati98 , I closed my last PR due to i mistakenly pushed the changes in the main branch instead to the new branch i have now pushed changes to the new branch ., Kindly review the changes .

**Comment by adiati98** [comment]
Hey @DevJSter ,
Can you please assign yourself to the issue?

**Comment by DevJSter** [comment]
.take

**Comment by DevJSter** [comment]
Hey @adiati98 , I've assigned myself to this issue . Can you please review the PR?
