### ISSUE TITLE
Bug: Sign up link to create OpenSauced account is not working

### ISSUE THREAD

**Issue by Lymah123** [open-sauced/docs#278]
### Describe the bug

The sign-up link to get started with OpenSauced is not working.

![image](https://github.com/open-sauced/docs/assets/109049037/6c1a879f-6c94-41ea-a95f-3b31458721f8)

Gives this;
![image](https://github.com/open-sauced/docs/assets/109049037/2c56badc-3da8-488f-8625-1bd2a29d7d40)

I tried like three different browsers, still not working. 
Besides, I can't log in to my OpenSauced account. 

### Steps to reproduce

1. Got to open source intro course
2. Click on how to contribute to the Open Source section. Better still, follow this link: 
https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=discovering-open-source-with-opensauced
4. Under discovering open source with OpenSauced
5. Click on the link that states sign up for an account.

### Browsers

Chrome, Firefox, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
Hi, @BekahHW  and @adiati98. 
Please let me know if I am the only one having an issue with my OpenSauced account.

**Comment by bdougie** [comment]
I wasn't able to reproduce on my end. Were you able to try without www. Perhaps was an mis fire or cache thing.

**Comment by BekahHW** [comment]
I'm also not able to reproduce it on my end. I typed it into my browser and clicked the link. What browser are you using? Can you try a different one?

**Comment by adiati98** [comment]
Hey @Lymah123,

I can't reproduce it because I have no problem opening the OpenSauced app as shown in the screen recording below.
Can you try https://app.opensauced.pizza ?

Also, this issue is supposed to be opened in the intro repo and not here at docs. 😊

https://github.com/open-sauced/docs/assets/45172775/d129dc61-77a2-464b-9c52-6f94fe667247
