### ISSUE TITLE
Add YOLO coder 

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#347]
- Let's add this to the glossary and repo page docs

**Comment by bdougie** [comment]
The current UI suggests that pushes to main might be a problem, but I am curious if this is a glossary will we be adding an opinion or suggestion in this context.

<img width="470" alt="Screenshot 2024-07-02 at 10 07 12 AM" src="https://github.com/open-sauced/docs/assets/5713670/66106fb0-e567-4946-9003-0e53013d481c">

My suggestion is we provide context on why pull requests are important for gathering context and storytelling for the future developer. The open source guide kind of provides context on this. https://opensource.guide/how-to-contribute/#opening-a-pull-request
