### ISSUE TITLE
Feature: Add an FAQ for how to improve your OSCR

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#368]
### Suggested solution

This should talk about how it's a holistic score and how there's no one way to improve it. Things to take into consideration include:

- engagement in GH
- Quality PRs that maintainers want
- completing contributions
- time off

**Comment by FatumaA** [comment]
Hi, 
Can I attempt this? 
I want to add docs to my contribs along with the UI and accessibility issues we discussed with Nick.

**Comment by BekahHW** [comment]
@FatumaA sure. Here are more details, and I'd like to expand the initial scope if that's ok.

## Issue Details
- Add an FAQ about how the OSCR is calculated
- Add a Guide to Improving Your OSCR 

## FAQ
- In docs>welcome>faqs.md add the following to the contributions section:
### 5. How is the OSCR calculated?
The OpenSauced Contributor Rating (OSCR) is calculated using a combination of factors that reflect a contributor's overall impact in open source. The OSCR considers contribution quality and consistency, community engagement, project impact, collaboration skills, ecosystem involvement, and reputation. These categories are evaluated over recent activity periods (90 days) to produce a comprehensive score that represents a contributor's value (out of 300 total points) to the open source community. 

## Add a Guide to Improving Your OSCR Score

1. In docs>opensauced-guides, add a file called `oscr-guide.md`
2. In sidebar.js, you need to add it to the OpenSauced Guides after the student's guide like this:
```
    {
      type: "category",
      label: "Student's Guide",
      collapsed: true,
      items: [
        "opensauced-guides/students-guide/students-guide",
      ],
    },
    // Add the new guide here
    "opensauced-guides/oscr-guide" 
  ],
},
```

## Create the OSCR Guide

1. You'll first need to add the frontmatter to the top of the file:
```
---
id: oscr-guide
title: "Guide to Improving Your OSCR"
sidebar_label: Guide to Improving Your OSCR
keywords: 
- "contributors"
- "guides"
- "how to contribute to open source"
- "OSCR score"
- "Make an impact in open source"
- "Open Source Contributor Rating"
- "Open Source Score"
---
```
2. Next you need to write about improving your score. Rather than just giving a list, I would recommend finding a way to categorize a section and then going into details and using lists within the sections. For example, one section might be "Pull Requests" and you list and go into detail on how to positively impact your score for pull requests in that section.

Here is a list of some ways to improve your score. 

- Open and merge pull requests: Each merged PR gives a significant boost 
- Create quality pull requests regularly: Opened PRs contribute to your score but having PRs closed quickly, as this can hurt your score 
- Avoid any behavior that could be flagged as spam: Spam flags severely impact your score 
- Contribute consistently over time: The score considers a 90-day window, so maintain regular activity
- Star repositories you genuinely intend to contribute to: Your score improves if you contribute to repos you've starred
- Fork repositories with the intention to contribute: Contributing to forked repos increases your score more than just forking
- Open meaningful issues: Creating issues adds to your sway score
- Engage in discussions: Commenting on issues and PRs increases your sway
- Provide thoughtful reviews on PRs: PR reviews contribute to your sway score
- React to issues and comments: Reactions are weighted slightly higher in the sway calculation
- Maintain a positive presence: Avoid any behavior that could be marked as spam, as it heavily penalizes your score
- Contribute across multiple areas: Engaging in issues, PRs, reviews, and comments all contribute to your overall score
- Be patient: Remember that the score considers a 90-day window, so consistent positive contributions will improve your score over time
- Focus on quality over quantity: While the number of contributions matters, ensuring they're valuable and well-received is important
- Collaborate effectively: Engaging in constructive discussions and reviews can boost your sway score
- Stay active: Regular activity, even if not daily, helps maintain a good score
- Help others: Reviewing PRs and commenting on issues contributes to your score, even if you're not the original author


I'm going to assign you the issue, but if this is too much for you to take on, let me know since the scope changed.

**Comment by FatumaA** [comment]
That's fine. I'll get to it :)

I wanted to actually come up with product docs content/architecture as well, to improve that muscle. Is there any other docs work going on in which I can take up more of an active role (under your approval of course)? Perhaps the new pizza cli needs documentation help?

**Comment by BekahHW** [comment]
@FatumaA if you think the CLI needs clearer docs, feel free to raise an issue.

One thing I've been thinking about but haven't gotten to is doing a bit of a reorg for docs. We have some Concepts at OpenSauced that I think are valuable but are getting lost in the other docs.

I would like to see a section for that. 

It should include things like:
- OSCR
- Contributor Confidence
- OpenSSF Score
- Lottery Factor
- Repositories as a Dataset

It doesn't need to be as thorough as [Understanding Repo Insights Data](https://opensauced.pizza/docs/maintainers/understanding-repo-insights/), but this is a decent enough example to show that with the section, users can 1. Understand what those concepts mean and 2. Understand why they're useful. 

It should go a little deeper than the glossary. Maybe be linked in the glossary, even. 

Let me know if you're interested in taking that on or if you would prefer to do that over this issue.

**Comment by FatumaA** [comment]
Hi,
Yes, I'd like to do too 😊

**Comment by adiati98** [comment]
Hey @FatumaA,
Those are great questions! Answering your questions:

- We are talking to contributors and orgs. Therefore, we are using:
   - "You" when we explain and walkthrough something (features, how-to, etc.)
   - "We" when we speak as OpenSauced (take a look at the first paragraph in the [Glossary](https://opensauced.pizza/docs/welcome/glossary/) as an example)
   - "I" in FAQs as it speaks through the audience's POV
- Our docs is using US English.
- OpenSauced features are started with capital letter. You can take a look at the "Features" section.

I hope this helps. Feel free to ask if you have more questions! ✨
