### ISSUE TITLE
Update Writers Guide

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#383]
Now that we've updated to the[ latest version of docusaurus](https://docusaurus.io/blog/releases/3.5), there are some directions that need to be updated here:

https://opensauced.pizza/docs/contributing/opensauced-writers-guide/writers-guide/.

The biggest change is with the authors.yml file. Let's update this based on the docusuarus documentation.

**Comment by shubhamchasing** [comment]
Hey @BekahHW, I would like to contribute to docs. Can you please assign me? This would be my first contribution to docs!

**Comment by shubhamchasing** [comment]
.take

**Comment by shubhamchasing** [comment]
Is this example fine, what else should I include in the example
![Screenshot from 2024-09-16 18-27-03](https://github.com/user-attachments/assets/9bc104cf-4b22-4d81-9278-320b1be2a882)


In the [update 3.5](https://docusaurus.io/blog/releases/3.5) there are other updates like

- https://docusaurus.io/blog/releases/3.5#blog-authors-pages
- https://docusaurus.io/blog/releases/3.5#blog-feeds-styling
- https://docusaurus.io/blog/releases/3.5#blog-sidebar-grouping and a few others

Please help me with what changes I should make, thank you!

**Comment by BekahHW** [comment]
@shubhamchasing great questions! Let's just add an admonition in the repeat authors section like this:

```
:::note

Please be sure to add  `page: true` to your author entry to generate your author page.
:::
```

In terms of the example, why don't we go with the first two entries in our current [authors.yml file](https://github.com/open-sauced/docs/blob/main/blog/authors.yml).

**Comment by shubhamchasing** [comment]
@BekahHW anything else is required? 
As you suggested, I included an admonition and all the details for the first entry, as well as some details from the second entry to keep the example concise [authers. yml](https://github.com/open-sauced/docs/blob/main/blog/authors.yml)

![Screenshot from 2024-09-20 20-37-31](https://github.com/user-attachments/assets/72189649-e1f0-44f4-a8cc-8da1d149552c)

**Comment by BekahHW** [comment]
That looks good to me, @shubhamchasing

**Comment by shubhamchasing** [comment]
> That looks good to me, @shubhamchasing

I have one query, I tried to find the dedicated author page like [slorber](https://docusaurus.io/blog/authors/slorber) but I could not find it, where can I find it?
