### ISSUE TITLE
Bug: Add truncate to blog posts

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#405]
### Describe the bug

When we started using docusaurus as our community blog, truncate wasn't added to some of the posts. Everything before truncate is visible on the page, with  Read more to open the full post. 

We need to add this to the following posts:

- [ ] "blog/2024/2024-04-16-creating-an-og-image-using-react-and-netlify-edge-functions.md"
- [ ] "blog/2024/2024-04-02-form-and-function-how-i-lost-my-submit-button-got-it-back.md"
- [ ] "blog/2024/2024-03-14-stuck-in-the-middle-with-you-an-intro-to-middleware.md"
- [ ] "blog/2024/2024-02-06-challenging-the-skeptics-unveiling-the-undeniable-goodness-of-tailwind-css.md"
- [ ] "blog/2024/2024-01-23-the-native-browser-dialog-element.md"
- [ ] "blog/2023/2023-12-14-migrating-from-jest-to-vitest-for-your-react-application.md"
- [ ] "blog/2023/2023-11-14-boost-productivity-with-the-github-cli.md"
- [ ] "blog/2023/2023-10-31-github-actions-a-maintainers-best-friend.md"
- [ ] "blog/2023/2023-09-21-supercharge-your-repository-with-code-owners.md"

### Steps to reproduce

1. For each of those, we need to add `<!-- truncate -->` after the first or second paragraph. You should add it where it makes sense to cut off the text, giving the reader enough information to understand what the blog post is about and interested in reading more. Here's an example:

> We've talked a lot about the challenges of being a maintainer, especially a solo maintainer. But like I say in our recent [newsletter](https://news.opensauced.pizza/why-open-source-is-a-team-sport/), open source is a team sport. But finding the right teammates can be a tricky situation as well. You might not get it right all of the time. And that's ok. Taking steps to make sure you and your project stay healthy can help to create a smoother and more rewarding open source experience. In this blog post, I'll provide a checklist and examples to help you build and manage an effective team for your open source project.
>
> `<!-- truncate -->`

**Comment by jmslynn** [comment]
.take

**Comment by DevvEmeka** [comment]
@BekahHW can I work on this issue?

**Comment by adiati98** [comment]
Hey @DevvEmeka,
This issue has been assigned. 🙂

**Comment by BekahHW** [comment]
Hey @jmslynn how are things going?

**Comment by jmslynn** [comment]
I'm sorry! My schedule is getting busier. Why don't you open this back up and allow someone else to take it during Hacktoberfest. If no one does, I'll get it done in early November.

**Comment by BekahHW** [comment]
Hey, @DevvEmeka, are you interested in picking this issue up?

**Comment by shubhamchasing** [comment]
Hey @BekahHW I would like to work on it

**Comment by shubhamchasing** [comment]
Hey @BekahHW please check
