### ISSUE TITLE
Feature: Add a section for Key Metrics Guide 

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#407]
### Suggested solution

We have some Concepts at OpenSauced that I think are valuable but are getting lost in the other docs.

I would like to see a section for that called Key Metrics Guide. 

It should include things like:
- OSCR
- Contributor Confidence
- OpenSSF Score
- Lottery Factor
- Repositories as a Dataset

It doesn't need to be as thorough as [Understanding Repo Insights Data](https://opensauced.pizza/docs/maintainers/understanding-repo-insights/), but this is a decent enough example to show that with the section, users can 1. Understand what those concepts mean and 2. Understand why they're useful. 

It should go a little deeper than the glossary. Maybe be linked in the glossary, even.

**Comment by BekahHW** [comment]
@FatumaA

**Comment by FatumaA** [comment]
.take

**Comment by FatumaA** [comment]
Hi Bekah! 
I will get to this in the next couple of days. 

I did look at it and was going to put it under "Getting Started." Is that okay, or should it be in its own section right below the "contributing guide" section?

**Comment by BekahHW** [comment]
@FatumaA, you can put it under Getting Started. I like that idea.
