### ISSUE TITLE
docs: add "hot.opensauced.pizza" category

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/docs#54]
### Type of feature

📝 Documentation

### Current behavior

Currently there is no category for hot repo.

### Suggested solution

Make a new category for the hot repo, and possibly make a new doc page in it called "Getting Started", which guides user through the installation and running the project (probably just clone the readme of the project, but without the extra steps that are not functioning like tests).

### Additional context

Similar to the Chrome extension guide we need user docs in the "Introduction to OpenSauced" section. 

- [ ] Voting
- [ ] Filtering
- [ ] Searching
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jeseekia** [comment]
.take

**Comment by 0-vortex** [comment]
@Deadreyo there should not be individual categories for every repository - these docs should be a getting started guide for technical and non-technical people, it could maybe describe the differences between our frontends and backends, but making one section for each of the other endpoints we are using is not adding any value just increasing the maintenance load for this repo 😅

**Comment by Deadreyo** [comment]
@0-vortex 
> @Deadreyo there should not be individual categories for every repository - these docs should be a getting started guide for technical and non-technical people, it could maybe describe the differences between our frontends and backends, but making one section for each of the other endpoints we are using is not adding any value just increasing the maintenance load for this repo 😅

The approach of separate categories would be more tidy and easier to know where to look at for specific documentations, for example would contain how to get the API key, and how supabase integrates with it, etc. (like the ones Janie had issues with).

So what's the layout or structure you have in mind?

**Comment by BekahHW** [comment]
@bdougie does it make sense to add a section for Hot in our docs?

**Comment by bdougie** [comment]
I am indifferent, but lean towards yes. I'd love to revive the project, but don't have bandwidth to focus on this and the extension at the moment. For now a brief intro to finding and voting projects is enough for now.

**Comment by jdwilkin4** [comment]
.take
