### ISSUE TITLE
docs: make new 2023 triage team guide

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs#84]
This one I will do, just making the issue to remember to do so.

**Comment by febr3s** [comment]
Hi! I was getting started on Open Sauce, and I ran into this end-road. I thought that my first contribution could be to edit the document where it sends you to comment on an archived discussion. Even if there is not an established workflow to join the team yet, I believe that suppressing thar outdated link might be a good first step.

**Comment by bdougie** [comment]
The new path is joining the discord and requesting in the contributor chat

**Comment by CBID2** [comment]
Can you elaborate further on how this doc will be outlined @bdougie?
