### ISSUE TITLE
docs: add insights guide

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs#92]
Similar to the Chrome extension guide we need user docs in the "Introduction to OpenSauced" section.

- [ ] highlights
- [ ] Insight pages
- [ ] Profile pages
- [ ] Settings
- [ ] Emails
- [ ] notifications

**Comment by CBID2** [comment]
Hey @bdougie. If this issue is still open, I can do user docs on the "highlights". I've been wanting to gain experience in doing product documentation(I've also been using this feature a lot so I'm pretty knowledgeable in it), and I feel like this would be a great way to start! 😄

**Comment by bdougie** [comment]
> Hey @bdougie. If this issue is still open, I can do user docs on the "highlights". I've been wanting to gain experience in doing product documentation(I've also been using this feature a lot so I'm pretty knowledgeable in it), and I feel like this would be a great way to start! 😄 

Yes this is still open. I'd love your assistance on this. Let me know if you have any questions.

**Comment by CBID2** [comment]
> > Hey @bdougie. If this issue is still open, I can do user docs on the "highlights". I've been wanting to gain experience in doing product documentation(I've also been using this feature a lot so I'm pretty knowledgeable in it), and I feel like this would be a great way to start! 😄 
> 
> Yes this is still open. I'd love your assistance on this. Let me know if you have any questions.

Will do
