### ISSUE TITLE
feat: add markprompt to docs site

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs#95]
https://markprompt.com/docs#docusaurus

I'll add more context later 😀

**Comment by Ant-Shell** [comment]
Hello @bdougie - first-time contributor here. I would be happy to work on this; what additional context should I be aware of?

**Comment by bdougie** [comment]
The only context is our algolia search does not work today and it would be ideal to leverage markprompt in lieu of the algolia.

Would love for you to provide more context and a suggestion for implementation after some research.

**Comment by Ant-Shell** [comment]
Thank you for the additional information! I'll .take this and start researching as soon as possible.

**Comment by Ant-Shell** [comment]
Hi @bdougie - here's an update on my research so far.

While looking into Markprompt, I got curious about what could be causing the current issue with Algolia so I did a little digging there first.

Per these [troubleshooting docs](https://www.algolia.com/doc/guides/managing-results/troubleshooting/troubleshooting-search/), I took a look at the network requests in Chrome dev tools and noticed a 403 error: `message: "Invalid Application-ID or API key"` - is there a [related dashboard](https://support.algolia.com/hc/en-us/articles/11217017604497-Why-am-I-getting-403-error-message-Invalid-Application-ID-or-API-key-status-403-with-DocSearch) where this information can be verified? 

(Current `appId` and `apiKey` can be seen [here](https://github.com/open-sauced/docs/blob/main/docusaurus.config.js) for comparison.)

Once Algolia is fixed, it seems that Markprompt + Algolia integration is the way to go per the [Markprompt docs](https://markprompt.com/docs#usage-with-algolia), as well as this [blog post](https://markprompt.com/blog/algolia). 

If indeed the `appId` and/or `apiKey` need(s) to be updated and I can be provided with the new value(s), I'd be more than happy to test all of this locally. (Might need an `indexName` value as well?)

<img width="1730" alt="Screenshot 2023-08-07 at 6 17 09 PM" src="https://github.com/open-sauced/docs/assets/100455148/9308abdd-1067-47ee-b726-f73292599f0e">

**Comment by bdougie** [comment]
The bad api key is due to is not paying for algolia. That won't get fixed as their cost is not something we are willing pay.

**Comment by Ant-Shell** [comment]
Ah, ok - thank you for the clarification. I'll pursue a different route.

**Comment by bdougie** [comment]
> Ah, ok - thank you for the clarification. I'll pursue a different route.

Just reading through this and confirmed the best path is algolia. I will need to explore the cost and if makes sense. I will take a look at this tomorrow on stream.

**Comment by Ant-Shell** [comment]
Hello @bdougie - just wanted to follow up on this issue. I would be happy to help however I can.

**Comment by bdougie** [comment]
@Ant-Shell thanks for the ping on this. I went ahead and installed the Algolia crawler plugin on this site on Netlify.

Let me know if this gets things moving forward.

![Screen Shot 2023-09-01 at 1 00 58 PM](https://github.com/open-sauced/docs/assets/5713670/9a458557-8006-4a8c-bd65-2608da964878)

**Comment by bdougie** [comment]
> @Ant-Shell thanks for the ping on this. I went ahead and installed the Algolia crawler plugin on this site on Netlify.
> 
> Let me know if this gets things moving forward.

Find me on discord if you have questions. You should be able to create your algolia account to test locally. Keys are set up in Netlify to test in deploy previews.

**Comment by Ant-Shell** [comment]
Hi @bdougie - thank you very much for the update and additional info!

I'm planning to take a look at this tomorrow, so if/when I have any questions I'll be sure to reach out 🙌

**Comment by BekahHW** [comment]
Hey @Ant-Shell I wanted to check in and see how things are going and if any of the things you chatted about in office hours a couple of weeks ago has helped.

**Comment by Ant-Shell** [comment]
Hi @BekahHW - sorry for the radio silence on this issue. I recently started and internship, so I'm working on adjusting to my new schedule. 

I did get some ideas from office hours, and hope to make continued progress over the weekend. Details on progress and plans below. Please let me know if there are questions or concerns.

 **So far I have done the following:**
- Created my own Algolia and Markprompt accounts
- Created my own Netlify account and linked it to my forked Open Sauced Docs repo
-  Linked my Algolia account to Netlify
- Set up Netlify to do branch deploys for new branches (this should allow me to preview updates)

**What I plan to do next:**
- Create a feature branch in my forked Docs repo and configure my local `docusaurus.config.js` file with my personal Algolia account values for testing.
- Push the branch to my forked repo and view the preview branch
- Keep making adjustments until I get a working Algolia search
- Attempt to add Markpromt, after Algolia search is working
- Report back with findings and discuss how to proceed from there

**I can also try the following:**
- Create a separate feature branch and try configuring my local `docusaurus.config.js` to use only Markpromt for searches, without Algolia configuration

**Comment by BekahHW** [comment]
Hey @OgDev-01 would you mind taking a look at this issue?

**Comment by Ant-Shell** [comment]
Wanted to follow up - I haven't had as much time as I was anticipating to work on this, my apologies. However, I wanted to leave various resources I found while researching and testing on and off. Hopefully they will be of use.

**Algolia troubleshooting resources and info:** 
- https://www.algolia.com/doc/integration/magento-2/troubleshooting/data-indexes-queues/?client=php
- https://www.algolia.com/doc/api-client/methods/indexing/
- https://www.algolia.com/doc/guides/getting-started/how-algolia-works/in-depth/ecosystem/#docsearch
- https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/prepare-data-in-depth/
- https://www.algolia.com/doc/tools/crawler/getting-started/overview/
- https://discourse.algolia.com/t/no-search-results-from-a-manually-created-index-for-docusaurus/17610
- https://www.algolia.com/doc/guides/sending-and-managing-data/manage-indices-and-apps/manage-indices/tutorial/generate-sitemap-from-index/
- https://github.com/algolia/algolia-sitemap
- https://docsearch.algolia.com/docs/tips
- https://docsearch.algolia.com/docs/templates

**Misc Algolia info:**
- https://www.algolia.com/pricing/
- https://www.algolia.com/for-open-source/
- https://docsearch.algolia.com/

**I was planning to try this next (per: https://www.youtube.com/watch?v=F_jqADu-izk):**
1. Generate a `site.xml` file locally
2. Push it up to a feature branch on my forked repo
3. Run algolia crawler on my feature branch to test populating indices

**If that worked, was planning to try integrating with Markpromt:**
- https://markprompt.com/docs#docusaurus
- https://github.com/motifland/markprompt-js/tree/main/examples/with-docusaurus
- https://github.com/motifland/markprompt-js/tree/main/examples/with-docusaurus-algolia

**Comment by bdougie** [comment]
Thanks for the details @Ant-Shell 

I have created an Algolia account and invited a few folks from @open-sauced/engineering. We can have @OgDev-01 pick this up when his bandwidth allows for it.
